### ISSUE TITLE
Background not filling vertical space

### ISSUE THREAD

**Issue by AlpriElse** [Stutive/stutive-ui#10]
https://stutive.slack.com/archives/CRLB3B5QD/p1577595709000200

cc/ @vibhav2799

**Comment by vibhav2799** [comment]
TY

**Comment by vibhav2799** [comment]
I still see this issue, tried different browsers. Your changes are not deployed perhaps?

**Comment by AlpriElse** [comment]
@vibhav2799 Now deployments got messed up when we went about renaming, just fixed it now
